"""Publish the Pindrop v4 portfolio: re-validate every file, pin hashes, archive the previous one.

The previous Coverline v3 manifest is preserved as docs/data/portfolio-coverage-v3.json and its files
stay downloadable, because the competition allows three uploads per week and earlier files remain
valid candidates for the one final selection.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import shutil
import zipfile
from pathlib import Path

import numpy as np
import rasterio
from PIL import Image

from .common import ROOT, read_json, sha256, utc_now, write_json
from .raster import template_info, validate_submission

PLAN = {
    "nodes": {"order": 1, "title": "Pindrop nodes", "badge": "SUBMIT FIRST", "role": "primary",
              "hypothesis": "The frozen winner: the same emitted-pixel budget as the dense ridge line, "
                            "but placed at the metric's kernel spacing so redundant mass is not paid for.",
              "answers": "Does the coverage-optimal placement beat the previous session's dense files "
                         "on the hidden expert labels?"},
    # Order is value, not experiment number: slots are limited to three per week, so the two files with
    # a measured reason to be believed are ranked above the control, and the control is published last
    # as an explicit test of the placement hypothesis on the real metric.
    "discovery": {"order": 2, "title": "Pindrop catalogue-gap target", "badge": "SUBMIT SECOND",
                  "role": "independent",
                  "hypothesis": "The same node layer generated by the arm trained only on catalogue "
                                "pixels the supplied labels do not contain, i.e. on the unmapped population.",
                  "answers": "Does a model trained on unmapped catalogued faults generalise to the "
                             "hidden expert labels better than one trained on everything?"},
    "ridge": {"order": 3, "title": "Pindrop dense ridge control", "badge": "CONTROL · UPLOAD LAST",
              "role": "control",
              "hypothesis": "The identical arm, budget, halo and tip with spacing 1: a dense one-pixel "
                            "ridge line, which is exactly what a confidence floor emits.",
              "answers": "ridge minus nodes is a controlled measurement of the sparse-placement "
                         "hypothesis on the real metric, at a fixed pixel budget."},
}
NOTE_MAX = 120  # our own brevity rule for the form's Note field; no official limit was verified
ARCHIVE = "portfolio-coverage-v3.json"


def check_variant_policies(report: dict) -> None:
    """Refuse a report whose recorded policy contradicts the variant it describes.

    Added after a reviewed run shipped the *selected node* policy on the dense-control file: the pixels
    were right, the record and the pasted Note were wrong, and only a human reading them side by side
    would have noticed. A control file is only a control if its own metadata says what it is.
    """
    selected = report["selected"]
    by_variant = {entry["variant"]: entry for entry in report["portfolio"]}
    if set(by_variant) != {"nodes", "ridge", "discovery"}:
        raise ValueError("Portfolio must contain exactly the nodes, ridge and discovery variants")
    keys = ("layer", "spacing", "budget", "halo", "tip")
    nodes, ridge = by_variant["nodes"], by_variant["ridge"]
    if {k: nodes["policy"][k] for k in keys} != {k: selected[k] for k in keys} or \
            nodes["arm"] != selected["arm"]:
        raise ValueError("The nodes file must record the frozen selected policy and arm")
    if ridge["policy"]["layer"] != "ridge" or ridge["policy"]["spacing"] != 1:
        raise ValueError("The dense control must record a ridge policy with spacing 1")
    if ridge["policy"]["budget"] != selected["budget"] or ridge["arm"] != selected["arm"]:
        raise ValueError("The dense control must use the selected budget and arm with suppression off")
    if ridge["note"] == nodes["note"]:
        raise ValueError("Every file needs its own Note")


def compact_note(entry: dict) -> str:
    """Validate the runner's paste-able Note: unique, hash-traceable and short enough to type."""
    note = str(entry["note"])
    if entry["sha256"][:10] not in note:
        raise ValueError("Note must carry the file's hash prefix")
    if len(note) > NOTE_MAX:
        raise ValueError(f"Note is {len(note)} characters; keep it under {NOTE_MAX}")
    return note


def preview(field: np.ndarray, valid: np.ndarray, sgmc: np.ndarray, dest: Path, factor: int = 5):
    h, w = field.shape
    hh, ww = (h + factor - 1) // factor, (w + factor - 1) // factor

    def pool(a):
        pad = np.zeros((hh * factor, ww * factor), dtype="float32")
        pad[:h, :w] = a
        return pad.reshape(hh, factor, ww, factor).max(axis=(1, 3)) > 0

    mask, model, published = pool(valid), pool(np.where(valid & ~sgmc, field, 0)), pool(sgmc & valid)
    rgba = np.zeros((hh, ww, 4), dtype="uint8")
    rgba[..., :3] = [24, 51, 49]
    rgba[..., 3] = mask * 255
    rgba[model] = [120, 220, 170, 255]
    rgba[published] = [245, 185, 80, 255]
    Image.fromarray(rgba).save(dest)


def publish(report_path: Path, docs: Path = ROOT / "docs") -> dict:
    report = read_json(report_path)
    run_dir = report_path.parent
    if report["strategy"] != "pindrop-v4":
        raise ValueError("This publisher only accepts the frozen pindrop-v4 experiment")
    check_variant_policies(report)
    template = ROOT / "data/sample_submission.tif"
    valid, _ = template_info(template)
    recorded = next(f["sha256"] for f in report["inputs"] if f["file"] == "sample_submission.tif")
    if sha256(template) != recorded:
        raise ValueError("Template differs from the experiment's recorded input")
    downloads = docs / "downloads"
    downloads.mkdir(parents=True, exist_ok=True)
    for old in downloads.glob("pindrop-v4-*"):
        old.unlink()  # only this publisher's own previous portfolio files
    items, seen_sha, nodes_field = [], set(), None
    for entry in report["portfolio"]:
        name, zname = entry["file"], entry["zip"]
        for n in (name, zname):
            if Path(n).name != n:
                raise ValueError("Unsafe filename")
        src = run_dir / name
        if sha256(src) != entry["sha256"]:
            raise ValueError(f"{name} changed after the experiment")
        check = validate_submission(src, template)
        if not check["passed"]:
            raise ValueError(f"{name} failed strict validation")
        if entry["sha256"] in seen_sha:
            raise ValueError("Portfolio files must be distinct")
        seen_sha.add(entry["sha256"])
        shutil.copyfile(src, downloads / name)
        shutil.copyfile(run_dir / zname, downloads / zname)
        with zipfile.ZipFile(downloads / zname) as z:
            if z.namelist() != [name] or hashlib.sha256(z.read(name)).hexdigest() != entry["sha256"]:
                raise ValueError("ZIP does not contain exactly the validated TIF")
        with rasterio.open(src) as r:
            field = r.read(1)
        inside = field[valid]
        if not (np.isfinite(inside).all() and inside.min() >= 0 and inside.max() <= 1):
            raise ValueError("Range check failed")
        if entry["variant"] == "nodes":
            nodes_field = np.where(valid, field, 0)
        plan = PLAN[entry["variant"]]
        items.append({**plan, "variant": entry["variant"], "file": f"downloads/{name}", "filename": name,
                      "zip": f"downloads/{zname}", "zip_sha256": sha256(downloads / zname),
                      "zip_bytes": (downloads / zname).stat().st_size,
                      "sha256": entry["sha256"], "bytes": entry["bytes"], "note": compact_note(entry),
                      "policy": entry["policy"], "arm": entry["arm"],
                      "emitted_pixels": entry["emitted_pixels"], "emitted_fraction": entry["emitted_fraction"],
                      "on_known_pixels": entry["on_known_pixels"], "different_pixels": entry["different_pixels"],
                      "checks_passed": sum(c["passed"] for c in check["checks"]),
                      "checks_total": len(check["checks"]), "validation": check,
                      "competition_score": None, "status": "unsubmitted; score unknown"})
    items.sort(key=lambda x: x["order"])
    if nodes_field is None:
        raise ValueError("The portfolio must contain the frozen node file")
    with rasterio.open(ROOT / "legacy/data/evidence/proxy/proxy_catalogue.tif") as r:
        sgmc_gap = r.read(1) == 2
    preview(nodes_field, valid, sgmc_gap, docs / "assets/pindrop-preview.png")
    current = docs / "data/portfolio.json"
    if current.exists():
        previous = read_json(current)
        if previous.get("strategy") != report["strategy"] and not (docs / "data" / ARCHIVE).exists():
            write_json(docs / "data" / ARCHIVE, previous)
    manifest = {"schema_version": 1, "published_at": utc_now(), "strategy": report["strategy"],
                "experiment_completed_at": report["completed_at"], "selected": report["selected"],
                "ridge_control": report["ridge_control"], "other_arm_candidate": report["other_arm_candidate"],
                "deployment": report["deployment"], "metric_algebra": report["metric_algebra"],
                "layer_comparison_tuning": report["layer_comparison_tuning"],
                "tranche_tuning": report["tranche_tuning"], "items": items,
                "rule": "Three uploads per week; one final selection for both rounds (official rules §3.5, §3.6.2).",
                "disclaimer": "Format-validated locally. No file here has a known competition score."}
    write_json(current, manifest)
    slim = {k: v for k, v in report.items() if k != "candidates"}
    slim["candidates"] = [{k: c[k] for k in ("arm", "layer", "spacing", "budget", "halo", "tip", "eligible",
                                             "emitted_fraction", "nodes_available", "robust_dti",
                                             "credit_per_emitted_pixel", "gap_dti", "all_dti", "known_dti",
                                             "far_dti")} for c in report["candidates"]]
    write_json(docs / "data/pindrop-experiment.json", slim)
    sources = read_json(ROOT / "research/sources.json")  # keep the published register in step
    write_json(docs / "data/sources.json", sources)
    with (docs / "data/source-catalog.csv").open("w", newline="", encoding="utf-8") as f:
        keys = ["id", "title", "publisher", "kind", "role", "access", "license", "used", "url"]
        writer = csv.DictWriter(f, keys, extrasaction="ignore", lineterminator="\n")
        writer.writeheader()
        writer.writerows(sources["sources"])
    print(f"Published {len(items)} Pindrop files; all strict format gates passed")
    return manifest


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    # The default names the run this publisher's release was built from. It is always printed, so a
    # stale directory can never be published silently; outputs/pindrop-v4-run1 is the reviewed run the
    # variant-policy guard refuses.
    ap.add_argument("--report", type=Path, default=ROOT / "outputs/pindrop-v4-run3/experiment.json")
    ap.add_argument("--docs", type=Path, default=ROOT / "docs")
    args = ap.parse_args()
    print(f"Publishing report {args.report.relative_to(ROOT)} sha256={sha256(args.report)[:16]}")
    publish(args.report, args.docs)


if __name__ == "__main__":
    main()
